sudo: required
services:
  - docker

before_install:
  - docker build -t charlesjlamb/docker-react -f Dcokerfile.dev .

script:
  - docker run charlesjlamb/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-878538045279"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_Access_Key
  secret_access_key:
    secure: "$AWS_Secret_Key"
